### ISSUE TITLE
请问原先的题库文件如何转码？

### ISSUE THREAD

**Issue by chchuj** [Benqalu/ultrasound-exam-library#1]
你好，我也从这个网站下载到一份题库，但它是以下乱码的格式，请问你当时是如何转码的？

``%7B%22errorCode%22%3A%220%22%2C%22errorMessage%22%3A%22%22%2C%22opFlag%22%3A%22true%22%2C%22serviceResult%22%3A%22%7B%5C%22paper%5C%22%3A%7B%5C%22paperId%5C%22%3A%5C%22000000006e179454016e35cd261554b5%5C%22%2C%5C%22paperName%5C%22%3A%5C%22%E4%B8%89%E5%9F%BA%E6%84%9F%E6%8E%A7%E9%A2%98%E5%BA%932019%5C%22%2C%5C%22totalQuestion%5C%22%3A70%2C%5C%22totalScore%5C%22%3A70%2C%5C%22timelimit%5C%22%3A%5C%22180%5C%22%2C%5C%22createTimeStr%5C%22%3A%5C%222019-11-04%2017%3A44%3A27%5C%22%2C%5C%22ownTotalScore%5C%22%3A0%2C%5C%22questions%5C%22%3A%5B%7B%5C%22topic%5C%22%3A%5C%22%E7%BB%8F%E7%A9%BA%E6%B0%94%E4%BC%A0%E6%92%AD%E7%96%BE%E7%97%85%E7%9A%84%E4%B8%BB%E8%A6%81%E9%A2%84%E9%98%B2%E7%AD%96%E7%95%A5%EF%BC%8C%E8%AF%B4%E6%B3%95%E9%94%99%E8%AF%AF%E7%9A%84%E6%98%AF%E5%93%AA%E9%A1%B9%3F%5C%22%2C%5C%22linkNo%5C%22%3A1%2C%5C%22answerAnalyse%5C%22%3A%5C%22%E5%9F%BA%E4%BA%8E%E7%BB%8F%E7%A9%BA%E6%B0%94%E4%BC%A0%E6%92%AD%E7%96%BE%E7%97%85%E7%9A%84%E4%BC%A0%E6%92%AD%E7%89%B9%E7%82%B9%EF%BC%8C%E5%BA

**Comment by Benqalu** [comment]
我没有转码，request.post出来就是解码好的。
不过硬要说的话，这是URL编码，参考：https://blog.csdn.net/sinat_35886587/article/details/80613618
